/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

package org.mozilla.fenix.components.tabgroupsuggestions

import android.content.Context
import androidx.datastore.core.DataStore
import androidx.datastore.core.Serializer
import androidx.datastore.dataStore
import kotlinx.coroutines.flow.first
import org.json.JSONArray
import org.json.JSONException
import org.json.JSONObject
import java.io.InputStream
import java.io.OutputStream

/**
 * The data persisted by the tab group suggestions feature across app restarts: which suggestions
 * the user has dismissed, and when each suggestion was last shown.
 *
 * @property dismissedSuggestionIds The [TabGroupSuggestion.id]s the user has dismissed. A
 * dismissed suggestion is never surfaced again, even if it would otherwise still be generated by
 * [TabGroupSuggestionEngine] on a later refresh.
 * @property lastShownTimestamps The wall clock time, in milliseconds, that each suggestion id was
 * last shown to the user. Used both for "shown" telemetry deduplication and to support a possible
 * future "don't show again for N days" preference.
 */
data class TabGroupSuggestionPreferencesData(
    val dismissedSuggestionIds: Set<String> = emptySet(),
    val lastShownTimestamps: Map<String, Long> = emptyMap(),
)

/**
 * Serializer for [TabGroupSuggestionPreferencesData], used by the [dataStore] that backs
 * [TabGroupSuggestionPreferences].
 *
 * A small hand-rolled JSON format is used instead of a compiled protocol buffer message, since the
 * data being persisted is a simple set and map of primitives; see
 * `org.mozilla.fenix.gleanplumb.OnDiskMessageMetadataStorage` for a similar precedent elsewhere in
 * this codebase.
 */
@Suppress("BlockingMethodInNonBlockingContext")
object TabGroupSuggestionPreferencesSerializer : Serializer<TabGroupSuggestionPreferencesData> {

    override val defaultValue: TabGroupSuggestionPreferencesData = TabGroupSuggestionPreferencesData()

    override suspend fun readFrom(input: InputStream): TabGroupSuggestionPreferencesData {
        return try {
            val json = JSONObject(input.readBytes().decodeToString())
            TabGroupSuggestionPreferencesData(
                dismissedSuggestionIds = json.optJSONArray(KEY_DISMISSED_IDS)?.toStringSet().orEmpty(),
                lastShownTimestamps = json.optJSONObject(KEY_LAST_SHOWN)?.toLongMap().orEmpty(),
            )
        } catch (e: JSONException) {
            defaultValue
        }
    }

    override suspend fun writeTo(t: TabGroupSuggestionPreferencesData, output: OutputStream) {
        val json = JSONObject().apply {
            put(KEY_DISMISSED_IDS, JSONArray(t.dismissedSuggestionIds.toList()))
            put(
                KEY_LAST_SHOWN,
                JSONObject().apply {
                    t.lastShownTimestamps.forEach { (id, timestamp) -> put(id, timestamp) }
                },
            )
        }
        output.write(json.toString().encodeToByteArray())
    }

    private fun JSONArray.toStringSet(): Set<String> =
        (0 until length()).map { index -> getString(index) }.toSet()

    private fun JSONObject.toLongMap(): Map<String, Long> =
        keys().asSequence().associateWith { key -> getLong(key) }

    private const val KEY_DISMISSED_IDS = "dismissedSuggestionIds"
    private const val KEY_LAST_SHOWN = "lastShownTimestamps"
}

/**
 * Application / process unique [DataStore] for IO operations related to tab group suggestions
 * preferences, following the same pattern as
 * `org.mozilla.fenix.datastore.pocketStoriesSelectedCategoriesDataStore`.
 */
private val Context.tabGroupSuggestionsDataStore: DataStore<TabGroupSuggestionPreferencesData> by dataStore(
    fileName = "tab_group_suggestions_preferences.json",
    serializer = TabGroupSuggestionPreferencesSerializer,
)

/**
 * Thin, suspend-friendly wrapper around the [DataStore] backing tab group suggestions
 * preferences, used by [DefaultTabGroupSuggestionRepository].
 *
 * @property context Used to look up the process-unique [DataStore] instance.
 */
class TabGroupSuggestionPreferences(private val context: Context) {

    /**
     * Reads the current [TabGroupSuggestionPreferencesData], suspending until at least one value
     * has been read from disk.
     */
    suspend fun data(): TabGroupSuggestionPreferencesData = context.tabGroupSuggestionsDataStore.data.first()

    /**
     * Atomically updates the persisted [TabGroupSuggestionPreferencesData] by applying
     * [transform] to the current value.
     */
    suspend fun update(
        transform: (TabGroupSuggestionPreferencesData) -> TabGroupSuggestionPreferencesData,
    ): TabGroupSuggestionPreferencesData {
        return context.tabGroupSuggestionsDataStore.updateData(transform)
    }
}
